name: "PR Branch Name"
description: "Sets the PR Branch Name for other steps"
inputs:
  repo-token:
    description: "GITHUB_TOKEN secret"
    required: true
  max-length:
    description: "Maximum length of the outputted branch name"
    required: false
    default: '25'
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-branch"
  color: "gray-dark"